# Introduction to AgentChat API with First AssistantAgent  
We’ll use the AgentChat API to create a simple `AssistantAgent` and explore its capabilities.  

In [2]:
from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.openai import OpenAIChatCompletionClient
from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.getenv('GEMINI_API_KEY')
# print("API Key:", api_key)  # Debugging line to check if the key is loaded correctly

In [3]:
gemini_model_client = OpenAIChatCompletionClient(model = 'gemini-1.5-flash-8b',api_key=api_key)

## Creating Our First AssistantAgent  
The `AssistantAgent` is a versatile agent for conversations, powered by AgentChat.  

In [4]:
geminiAssistant = AssistantAgent(name = "assistant",model_client=gemini_model_client,description='A Basic first Agent')

## Testing the AssistantAgent  
We’ll use the `run` method to send a task and get a response.  

In [5]:
result = await geminiAssistant.run(task="What's the capital of India?")

print(result)

messages=[TextMessage(id='d9143c85-c4ab-489d-931c-90b675ec9d98', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 8, 24, 6, 58, 20, 825749, tzinfo=datetime.timezone.utc), content="What's the capital of India?", type='TextMessage'), TextMessage(id='105f31e7-284b-4b2f-8380-640f6cecd025', source='assistant', models_usage=RequestUsage(prompt_tokens=32, completion_tokens=6), metadata={}, created_at=datetime.datetime(2025, 8, 24, 6, 58, 28, 346927, tzinfo=datetime.timezone.utc), content='New Delhi\n\nTERMINATE\n', type='TextMessage')] stop_reason=None


messages=[TextMessage(id='d9143c85-c4ab-489d-931c-90b675ec9d98', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 8, 24, 6, 58, 20, 825749, tzinfo=datetime.timezone.utc), content="What's the capital of India?", type='TextMessage'), TextMessage(id='105f31e7-284b-4b2f-8380-640f6cecd025', source='assistant', models_usage=RequestUsage(prompt_tokens=32, completion_tokens=6), metadata={}, created_at=datetime.datetime(2025, 8, 24, 6, 58, 28, 346927, tzinfo=datetime.timezone.utc), content='New Delhi\n\nTERMINATE\n', type='TextMessage')] stop_reason=None

In [6]:
print(result.messages)

[TextMessage(id='d9143c85-c4ab-489d-931c-90b675ec9d98', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 8, 24, 6, 58, 20, 825749, tzinfo=datetime.timezone.utc), content="What's the capital of India?", type='TextMessage'), TextMessage(id='105f31e7-284b-4b2f-8380-640f6cecd025', source='assistant', models_usage=RequestUsage(prompt_tokens=32, completion_tokens=6), metadata={}, created_at=datetime.datetime(2025, 8, 24, 6, 58, 28, 346927, tzinfo=datetime.timezone.utc), content='New Delhi\n\nTERMINATE\n', type='TextMessage')]


In [7]:
print(result.messages[-1].content)

New Delhi

TERMINATE



### Lets Use **OLLAMA**

In [8]:
from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.ollama import OllamaChatCompletionClient
from dotenv import load_dotenv
import os

load_dotenv()

True

In [9]:
ollama_model_client = OllamaChatCompletionClient(model = 'llama3')

In [10]:
ollamaAssistant = AssistantAgent(name = "assistant",model_client=ollama_model_client,description='A Basic Ollama first Agent')

In [11]:
result = await ollamaAssistant.run(task="What's the capital of India?")

In [14]:
print(result)

messages=[TextMessage(id='3ee388ed-4b8a-4e9f-b23f-9779e871a025', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 8, 24, 7, 6, 49, 51024, tzinfo=datetime.timezone.utc), content="What's the capital of India?", type='TextMessage'), TextMessage(id='7e6a7861-ab2d-4b06-9a16-3aba48d6754b', source='assistant', models_usage=RequestUsage(prompt_tokens=46, completion_tokens=9), metadata={}, created_at=datetime.datetime(2025, 8, 24, 7, 6, 56, 283503, tzinfo=datetime.timezone.utc), content='The capital of India is New Delhi!', type='TextMessage')] stop_reason=None


In [15]:
print(result.messages[-1].content)

The capital of India is New Delhi!
